app = "php-travels"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[mounts]]
source = "jenkinsdata"
destination = "/var/jenkins_home"