pipeline {
    agent any

    tools {
        maven 'Maven 3.8.6' // Make sure this matches the name in Jenkins' Global Tool Config
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }

    post {
        always {
            // This will publish test reports generated by maven-surefire-plugin
            junit '**/target/surefire-reports/*.xml'
        }
        failure {
            echo 'Build failed. Check test results and logs.'
        }
    }
}